    drop table tb_profile if exists;
    
    drop table tb_user if exists;

    drop table tb_profile if exists;


   
    create table tb_profile (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    
    create table tb_user (
       id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    
    create table tb_user_profiles (
       tb_user_id bigint not null,
        profiles_id bigint not null
    );
    

    alter table tb_user_profiles 
       add constraint FK86pua9rf6p0cap281evnxd052 
       foreign key (profiles_id) 
       references tb_profile;
    
    alter table tb_user_profiles 
       add constraint FK3vbrck8ry2vd45m68nfhswqy0 
       foreign key (tb_user_id) 
       references tb_user;