    drop table accessory if exists;
    
    drop table accessory_bike if exists;

    drop table bike if exists;

    drop table tb_profile if exists;
    
    drop table tb_user if exists;

    drop table tb_profile if exists;


   
    create table tb_profile (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    
    create table tb_user (
       id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    
    create table tb_user_profiles (
       tb_user_id bigint not null,
        profiles_id bigint not null
    );
    
    
    create table accessory (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );
    
    create table accessory_bike (
       id_bike bigint not null,
       id_accessory bigint not null
    );
    
    create table bike (
       id bigint generated by default as identity,
        modality varchar(255),
        distance varchar(255),
        primary key (id)
    );
    
    alter table accessory_bike 
       add constraint FK4rwoc20y4irvadrqh8dqbvq9y 
       foreign key (id_accessory) 
       references accessory;
    
    alter table accessory_bike 
       add constraint FKpb46x12fnyfq9t43fd20pqgao 
       foreign key (id_bike) 
       references bike;

    alter table tb_user_profiles 
       add constraint FK86pua9rf6p0cap281evnxd052 
       foreign key (profiles_id) 
       references tb_profile;
    
    alter table tb_user_profiles 
       add constraint FK3vbrck8ry2vd45m68nfhswqy0 
       foreign key (tb_user_id) 
       references tb_user;